providers = ["python"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[phases.build]
cmds = [". /opt/venv/bin/activate", "python src/agent.py download-files"]

[start]
cmd = "python src/agent.py start"
